services:
  - type: web
    name: ai-study-buddy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.10.13
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
